workaround: call `HostIdentifier.getHostName()` before opening a browser
... to avoid calling it during initialization of class WebDriverException which causes mysterious NoClassDefFoundError, see https://github.com/SeleniumHQ/selenium/issues/9784