don't check that browser took a screenshot
sometimes Firefox fails to take a screenshot because of such error:

```
WebDriverException: [Exception... "Data conversion failed because significant data would be lost"  nsresult: "0x80460003 (NS_ERROR_LOSS_OF_SIGNIFICANT_DATA)"  location: "<unknown>"  data: no]
Build info: version: '4.1.3', revision: '7b1ebf28ef'
System info: host: 'fv-az214-334', ip: '10.1.0.75', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-1017-azure', java.version: '17.0.2'
```