run tests on proper Chrome instead of Snap Chromium
Hope to fix these random issues on GitHub actions:

 PrintPageTest > onPrinter() FAILED
      org.openqa.selenium.InvalidArgumentException: invalid argument
      from unknown error: unhandled inspector error: {"code":-32000,"message":"Printing failed"}
        (Session info: chrome=147.0.7727.55)